"""Contracts for the published Codegen worker dependency gate."""

from __future__ import annotations

import importlib.util
import json
import sys
from datetime import date
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
CODEGEN_DIR = REPO_ROOT / "services" / "codegen"


def _load_script(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


audit_gate = _load_script(
    "codegen_worker_dependency_audit",
    CODEGEN_DIR / "scripts" / "audit_worker_dependencies.py",
)
aider_distribution = _load_script(
    "codegen_aider_distribution",
    CODEGEN_DIR / "scripts" / "verify_aider_distribution.py",
)

POLICY_PATH = CODEGEN_DIR / "dependency-audit-suppressions.json"
POLICY_DATE = date(2026, 7, 23)
EXPECTED_LOCKED_VERSIONS = {
    "aider-chat": "0.86.2",
    "aiohttp": "3.14.2",
    "click": "8.3.3",
    "diskcache": "5.6.3",
    "fastapi": "0.139.2",
    "gitpython": "3.1.53",
    "idna": "3.15",
    "importlib-metadata": "8.9.0",
    "litellm": "1.85.0",
    "pillow": "12.3.0",
    "pygments": "2.20.0",
    "python-dotenv": "1.2.2",
    "requests": "2.34.2",
    "soupsieve": "2.8.4",
    "starlette": "1.3.1",
    "urllib3": "2.7.0",
    "uv": "0.11.29",
}


def _policy() -> dict:
    return json.loads(POLICY_PATH.read_text(encoding="utf-8"))


def _write_policy(tmp_path: Path, policy: dict) -> Path:
    path = tmp_path / "suppressions.json"
    path.write_text(
        json.dumps(policy, indent=2) + "\n",
        encoding="utf-8",
    )
    return path


def _suppressions():
    return audit_gate.load_suppressions(POLICY_PATH, today=POLICY_DATE)


def _report(suppressions=None) -> dict:
    entries = suppressions or _suppressions()
    return {
        "dependencies": [
            {
                "name": suppression.package,
                "version": suppression.version,
                "vulns": [
                    {
                        "id": suppression.advisory_id,
                        "fix_versions": [],
                        "aliases": [],
                        "description": "Reviewed no-fix advisory.",
                    }
                ],
            }
            for suppression in entries
        ],
        "fixes": [],
    }


def test_worker_lock_is_fresh_against_canonical_security_inputs() -> None:
    lock_text = (CODEGEN_DIR / "requirements-agent.lock").read_text(
        encoding="utf-8"
    )
    locked = audit_gate.parse_locked_versions(lock_text)

    assert lock_text.startswith(audit_gate.LOCK_HEADER)
    assert {
        package: next(iter(locked[package]))
        for package in EXPECTED_LOCKED_VERSIONS
    } == EXPECTED_LOCKED_VERSIONS

    command = audit_gate.lock_compile_command(Path("/tmp/generated.lock"))
    assert command[:5] == (
        "uv",
        "pip",
        "compile",
        "pyproject.toml",
        "--extra",
    )
    assert "--constraints" in command
    assert "--overrides" in command
    assert "--python-version" in command
    assert "--universal" in command
    assert "--generate-hashes" in command

    generated_with_other_output = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    different output path\n"
        + "".join(lock_text.splitlines(keepends=True)[2:])
    )
    audit_gate.validate_generated_lock(lock_text, generated_with_other_output)
    with pytest.raises(audit_gate.AuditGateError, match="stale"):
        audit_gate.validate_generated_lock(
            lock_text,
            generated_with_other_output + "# changed\n",
        )


def test_security_inputs_are_exact_and_do_not_duplicate_schema() -> None:
    constraints = {
        line
        for line in (
            CODEGEN_DIR / "requirements-agent.constraints.txt"
        ).read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    }
    overrides = {
        line
        for line in (
            CODEGEN_DIR / "requirements-agent.overrides.txt"
        ).read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    }

    assert constraints == {"aider-chat==0.86.2", "diskcache==5.6.3"}
    assert overrides == {
        "aiohttp==3.14.2",
        "click==8.3.3",
        "fastapi==0.139.2",
        "gitpython==3.1.53",
        "idna==3.15",
        "importlib-metadata>=8,<9",
        "litellm==1.85.0",
        "pillow==12.3.0",
        "pygments==2.20.0",
        "python-dotenv==1.2.2",
        "requests==2.34.2",
        "soupsieve==2.8.4",
        "starlette==1.3.1",
        "urllib3==2.7.0",
    }
    assert constraints.isdisjoint(overrides)
    assert '"uv==0.11.29"' in (
        CODEGEN_DIR / "pyproject.toml"
    ).read_text(encoding="utf-8")


def test_suppression_schema_rejects_unknown_and_mismatched_entries(
    tmp_path: Path,
) -> None:
    policy = _policy()
    policy["bypass"] = True
    with pytest.raises(audit_gate.AuditGateError, match="unknown=.*bypass"):
        audit_gate.load_suppressions(
            _write_policy(tmp_path, policy),
            today=POLICY_DATE,
        )

    policy = _policy()
    policy["suppressions"][0]["version"] = "0.86.3"
    with pytest.raises(audit_gate.AuditGateError, match="identity mismatch"):
        audit_gate.load_suppressions(
            _write_policy(tmp_path, policy),
            today=POLICY_DATE,
        )

    policy = _policy()
    policy["suppressions"][0]["advisory_id"] = "PYSEC-2099-1"
    with pytest.raises(audit_gate.AuditGateError, match="unapproved"):
        audit_gate.load_suppressions(
            _write_policy(tmp_path, policy),
            today=POLICY_DATE,
        )

    policy = _policy()
    policy["suppressions"][0]["expires_on"] = "2099-12-31"
    with pytest.raises(audit_gate.AuditGateError, match="time bounds mismatch"):
        audit_gate.load_suppressions(
            _write_policy(tmp_path, policy),
            today=POLICY_DATE,
        )


def test_suppressions_fail_at_expiry_and_after_review(tmp_path: Path) -> None:
    with pytest.raises(audit_gate.AuditGateError, match="expired"):
        audit_gate.load_suppressions(
            POLICY_PATH,
            today=date(2026, 10, 21),
        )
    with pytest.raises(audit_gate.AuditGateError, match="review is overdue"):
        audit_gate.load_suppressions(
            POLICY_PATH,
            today=date(2026, 8, 23),
        )


def test_audit_report_allows_only_present_exact_no_fix_advisories() -> None:
    suppressions = _suppressions()
    audit_gate.validate_audit_report(_report(suppressions), suppressions)

    fixable = _report(suppressions)
    fixable["dependencies"][0]["vulns"][0]["fix_versions"] = ["0.86.3"]
    with pytest.raises(audit_gate.AuditGateError, match="now has a fix"):
        audit_gate.validate_audit_report(fixable, suppressions)

    unexpected = _report(suppressions)
    unexpected["dependencies"].append(
        {
            "name": "requests",
            "version": "2.34.2",
            "vulns": [
                {
                    "id": "PYSEC-2099-2",
                    "fix_versions": ["2.34.3"],
                    "aliases": [],
                    "description": "Unexpected fixable vulnerability.",
                }
            ],
        }
    )
    with pytest.raises(
        audit_gate.AuditGateError,
        match="unexpected fixable vulnerability",
    ):
        audit_gate.validate_audit_report(unexpected, suppressions)

    stale = _report(suppressions)
    stale["dependencies"].pop()
    with pytest.raises(audit_gate.AuditGateError, match="stale or missing"):
        audit_gate.validate_audit_report(stale, suppressions)


def test_audit_report_rejects_unknown_external_schema_fields() -> None:
    report = _report()
    report["dependencies"][0]["vulns"][0]["severity"] = "high"
    with pytest.raises(audit_gate.AuditGateError, match="unknown=.*severity"):
        audit_gate.validate_audit_report(report, _suppressions())


def test_aider_suppressions_are_bound_to_absent_dev_build_files() -> None:
    files = ("aider/__init__.py", "aider/main.py")
    aider_distribution.verify_file_manifest("0.86.2", files)

    for vulnerable_file in ("aider/auth.py", "aider/api_docs.py"):
        with pytest.raises(
            aider_distribution.AiderDistributionError,
            match="development files",
        ):
            aider_distribution.verify_file_manifest(
                "0.86.2",
                (*files, vulnerable_file),
            )
    with pytest.raises(
        aider_distribution.AiderDistributionError,
        match="expected aider-chat",
    ):
        aider_distribution.verify_file_manifest("0.86.3.dev0", files)

    policy = _policy()
    aider_entries = [
        entry
        for entry in policy["suppressions"]
        if entry["package"] == "aider-chat"
    ]
    assert {entry["advisory_id"] for entry in aider_entries} == {
        "PYSEC-2026-2335",
        "PYSEC-2026-2336",
    }
    assert all(entry["version"] == "0.86.2" for entry in aider_entries)


def test_diskcache_suppression_requires_hardened_h12_evidence() -> None:
    policy = _policy()
    diskcache = next(
        entry
        for entry in policy["suppressions"]
        if entry["advisory_id"] == "PYSEC-2026-2447"
    )

    assert diskcache["package"] == "diskcache"
    assert diskcache["version"] == "5.6.3"
    assert set(diskcache["evidence"]) == set(
        audit_gate.APPROVED_SUPPRESSIONS["PYSEC-2026-2447"].evidence
    )

    launcher = (
        CODEGEN_DIR / "app" / "editor" / "aider_launcher.py"
    ).read_text(encoding="utf-8")
    assert '_single_value(arguments, "--map-tokens") != "0"' in launcher
    assert "Aider repository map must be disabled" in launcher


def test_ci_local_and_release_paths_cannot_bypass_worker_gate() -> None:
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(
        encoding="utf-8"
    )
    local_audit = (REPO_ROOT / "scripts" / "audit_dependencies.sh").read_text(
        encoding="utf-8"
    )
    release = (REPO_ROOT / ".github" / "workflows" / "release.yml").read_text(
        encoding="utf-8"
    )

    gate = "services/codegen/scripts/audit_worker_dependencies.sh"
    assert "python-dependency-audit:" in ci
    assert f"run: {gate}" in ci
    assert "services/codegen/requirements-agent.lock" not in ci
    assert f'"$ROOT_DIR/{gate}"' in local_audit
    assert "services/codegen/requirements-agent.lock \\" not in local_audit
    assert "uses: ./.github/workflows/ci.yml" in release
    assert "build-artifacts:\n    name: Build Release Artifacts\n    needs: ci" in release


def test_clean_command_uses_python_312_strict_hash_audit() -> None:
    command = audit_gate.clean_audit_command(_suppressions())

    assert command[:8] == (
        "uvx",
        "--python",
        "3.12",
        "pip-audit",
        "--strict",
        "--require-hashes",
        "--disable-pip",
        "--ignore-vuln",
    )
    assert command.count("--ignore-vuln") == 3
    assert command[-2] == "-r"
    assert command[-1].endswith(
        "services/codegen/requirements-agent.lock"
    )
