#!/usr/bin/env python3
"""Fail-closed dependency audit gate for the published Codegen worker."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

SCRIPT_DIR = Path(__file__).resolve().parent
CODEGEN_DIR = SCRIPT_DIR.parent
REPO_ROOT = CODEGEN_DIR.parents[1]
LOCK_PATH = CODEGEN_DIR / "requirements-agent.lock"
CONSTRAINTS_PATH = CODEGEN_DIR / "requirements-agent.constraints.txt"
OVERRIDES_PATH = CODEGEN_DIR / "requirements-agent.overrides.txt"
SUPPRESSIONS_PATH = CODEGEN_DIR / "dependency-audit-suppressions.json"

SCHEMA = "apdl-codegen-dependency-audit-suppressions@1"
LOCK_REPOSITORY_PATH = "services/codegen/requirements-agent.lock"
LOCK_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv pip compile pyproject.toml --extra agent "
    "--constraints requirements-agent.constraints.txt "
    "--overrides requirements-agent.overrides.txt "
    "--python-version 3.12 --universal --generate-hashes "
    "--output-file requirements-agent.lock\n"
)
TOP_LEVEL_FIELDS = frozenset({"schema", "lock_file", "suppressions"})
SUPPRESSION_FIELDS = frozenset(
    {
        "advisory_id",
        "package",
        "version",
        "justification",
        "evidence",
        "owner",
        "review_by",
        "expires_on",
    }
)
REPORT_FIELDS = frozenset({"dependencies", "fixes"})
DEPENDENCY_FIELDS = frozenset({"name", "version", "vulns"})
VULNERABILITY_FIELDS = frozenset(
    {"id", "fix_versions", "aliases", "description"}
)
PACKAGE_LINE = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^;\\\s]+)(?:\s*\\)?$"
)


class AuditGateError(RuntimeError):
    """A worker dependency audit contract was not satisfied."""


@dataclass(frozen=True)
class ApprovedSuppression:
    package: str
    version: str
    evidence: frozenset[str]
    owner: str
    review_by: date
    expires_on: date


@dataclass(frozen=True)
class Suppression:
    advisory_id: str
    package: str
    version: str
    justification: str
    evidence: tuple[str, ...]
    owner: str
    review_by: date
    expires_on: date


@dataclass(frozen=True)
class Finding:
    advisory_id: str
    package: str
    version: str
    aliases: tuple[str, ...]
    fix_versions: tuple[str, ...]


_AIDER_EVIDENCE = frozenset(
    {
        (
            "services/codegen/scripts/verify_aider_distribution.py"
            "::verify_installed_distribution"
        ),
        (
            "services/codegen/tests/test_worker_dependency_audit.py"
            "::test_aider_suppressions_are_bound_to_absent_dev_build_files"
        ),
        (
            "services/codegen/tests/test_container_reproducibility.py"
            "::test_worker_uses_immutable_images_snapshot_packages_and_hash_lock"
        ),
    }
)
_SUPPRESSION_OWNER = "@Sukhikhk"
_SUPPRESSION_REVIEW_BY = date(2026, 8, 22)
_SUPPRESSION_EXPIRES_ON = date(2026, 10, 21)
APPROVED_SUPPRESSIONS: Mapping[str, ApprovedSuppression] = {
    "PYSEC-2026-2335": ApprovedSuppression(
        package="aider-chat",
        version="0.86.2",
        evidence=_AIDER_EVIDENCE,
        owner=_SUPPRESSION_OWNER,
        review_by=_SUPPRESSION_REVIEW_BY,
        expires_on=_SUPPRESSION_EXPIRES_ON,
    ),
    "PYSEC-2026-2336": ApprovedSuppression(
        package="aider-chat",
        version="0.86.2",
        evidence=_AIDER_EVIDENCE,
        owner=_SUPPRESSION_OWNER,
        review_by=_SUPPRESSION_REVIEW_BY,
        expires_on=_SUPPRESSION_EXPIRES_ON,
    ),
    "PYSEC-2026-2447": ApprovedSuppression(
        package="diskcache",
        version="5.6.3",
        evidence=frozenset(
            {
                (
                    "services/codegen/app/editor/aider_launcher.py"
                    "::validate_invocation"
                ),
                (
                    "services/codegen/tests/test_aider_launcher.py"
                    "::test_launcher_rejects_cache_and_control_bypass_options"
                ),
                (
                    "services/codegen/tests/test_worker_noexec_contracts.py"
                    "::test_hardened_aider_launcher_ignores_repository_and_home_control_files"
                ),
            }
        ),
        owner=_SUPPRESSION_OWNER,
        review_by=_SUPPRESSION_REVIEW_BY,
        expires_on=_SUPPRESSION_EXPIRES_ON,
    ),
}


def _canonical_package_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def _exact_fields(value: Any, expected: frozenset[str], context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise AuditGateError(f"{context} must be an object")
    actual = frozenset(value)
    if actual != expected:
        missing = sorted(expected - actual)
        unknown = sorted(actual - expected)
        raise AuditGateError(
            f"{context} fields do not match schema; "
            f"missing={missing}, unknown={unknown}"
        )
    return value


def _string(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise AuditGateError(f"{context} must be a non-empty string")
    return value


def _string_list(value: Any, context: str) -> tuple[str, ...]:
    if not isinstance(value, list):
        raise AuditGateError(f"{context} must be a list")
    result = tuple(_string(item, f"{context} entry") for item in value)
    if len(result) != len(set(result)):
        raise AuditGateError(f"{context} contains duplicate entries")
    return result


def _iso_date(value: Any, context: str) -> date:
    raw = _string(value, context)
    try:
        parsed = date.fromisoformat(raw)
    except ValueError as exc:
        raise AuditGateError(f"{context} must be an ISO calendar date") from exc
    if parsed.isoformat() != raw:
        raise AuditGateError(f"{context} must use canonical YYYY-MM-DD form")
    return parsed


def _validate_evidence_reference(reference: str, repo_root: Path) -> None:
    path_value, separator, symbol = reference.partition("::")
    if separator != "::" or not symbol or Path(path_value).is_absolute():
        raise AuditGateError(f"invalid evidence reference: {reference}")
    path = repo_root / path_value
    try:
        path.resolve(strict=True).relative_to(repo_root.resolve(strict=True))
    except (OSError, ValueError) as exc:
        raise AuditGateError(f"missing or escaped evidence reference: {reference}") from exc
    if not path.is_file():
        raise AuditGateError(f"evidence reference is not a file: {reference}")
    source = path.read_text(encoding="utf-8")
    definition = re.compile(
        rf"^(?:async\s+)?def\s+{re.escape(symbol)}\s*\(",
        re.MULTILINE,
    )
    if definition.search(source) is None:
        raise AuditGateError(f"evidence symbol is missing: {reference}")


def load_suppressions(
    path: Path = SUPPRESSIONS_PATH,
    *,
    repo_root: Path = REPO_ROOT,
    today: date | None = None,
) -> tuple[Suppression, ...]:
    """Load the exact approved suppression set and enforce its time bounds."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise AuditGateError(f"cannot load suppression policy: {path}") from exc
    document = _exact_fields(raw, TOP_LEVEL_FIELDS, "suppression policy")
    if document["schema"] != SCHEMA:
        raise AuditGateError("unknown suppression policy schema")
    if document["lock_file"] != LOCK_REPOSITORY_PATH:
        raise AuditGateError("suppression policy targets an unexpected lock")
    entries = document["suppressions"]
    if not isinstance(entries, list):
        raise AuditGateError("suppressions must be a list")

    current = today or datetime.now(timezone.utc).date()
    suppressions: list[Suppression] = []
    seen: set[str] = set()
    for index, raw_entry in enumerate(entries):
        entry = _exact_fields(
            raw_entry,
            SUPPRESSION_FIELDS,
            f"suppression {index}",
        )
        advisory_id = _string(entry["advisory_id"], "advisory_id")
        if advisory_id in seen:
            raise AuditGateError(f"duplicate suppression: {advisory_id}")
        approved = APPROVED_SUPPRESSIONS.get(advisory_id)
        if approved is None:
            raise AuditGateError(f"unapproved advisory suppression: {advisory_id}")

        package = _canonical_package_name(_string(entry["package"], "package"))
        version = _string(entry["version"], "version")
        if package != approved.package or version != approved.version:
            raise AuditGateError(
                f"suppression identity mismatch for {advisory_id}: "
                f"{package}=={version}"
            )
        evidence = _string_list(entry["evidence"], "evidence")
        if frozenset(evidence) != approved.evidence:
            raise AuditGateError(
                f"suppression evidence mismatch for {advisory_id}"
            )
        for reference in evidence:
            _validate_evidence_reference(reference, repo_root)

        justification = _string(entry["justification"], "justification")
        if len(justification) < 80:
            raise AuditGateError(
                f"suppression justification is incomplete for {advisory_id}"
            )
        owner = _string(entry["owner"], "owner")
        if owner != approved.owner:
            raise AuditGateError(f"unexpected suppression owner: {owner}")
        review_by = _iso_date(entry["review_by"], "review_by")
        expires_on = _iso_date(entry["expires_on"], "expires_on")
        if (
            review_by != approved.review_by
            or expires_on != approved.expires_on
        ):
            raise AuditGateError(
                f"suppression time bounds mismatch for {advisory_id}"
            )
        if review_by > expires_on:
            raise AuditGateError(
                f"review date follows expiry for {advisory_id}"
            )
        if current >= expires_on:
            raise AuditGateError(
                f"suppression expired for {advisory_id}: {expires_on}"
            )
        if current > review_by:
            raise AuditGateError(
                f"suppression review is overdue for {advisory_id}: {review_by}"
            )
        suppressions.append(
            Suppression(
                advisory_id=advisory_id,
                package=package,
                version=version,
                justification=justification,
                evidence=evidence,
                owner=owner,
                review_by=review_by,
                expires_on=expires_on,
            )
        )
        seen.add(advisory_id)

    expected = frozenset(APPROVED_SUPPRESSIONS)
    if frozenset(seen) != expected:
        raise AuditGateError(
            "suppression set is incomplete; "
            f"missing={sorted(expected - seen)}, unknown={sorted(seen - expected)}"
        )
    return tuple(suppressions)


def parse_locked_versions(lock_text: str) -> dict[str, frozenset[str]]:
    """Extract exact package versions from the generated requirements lock."""
    versions: dict[str, set[str]] = {}
    for line in lock_text.splitlines():
        match = PACKAGE_LINE.fullmatch(line)
        if match is None:
            continue
        package = _canonical_package_name(match.group(1))
        versions.setdefault(package, set()).add(match.group(2))
    return {package: frozenset(values) for package, values in versions.items()}


def validate_suppression_lock_versions(
    suppressions: Iterable[Suppression],
    lock_text: str,
) -> None:
    """Bind each advisory exception to one exact version in this lock."""
    locked = parse_locked_versions(lock_text)
    for suppression in suppressions:
        actual = locked.get(suppression.package, frozenset())
        expected = frozenset({suppression.version})
        if actual != expected:
            raise AuditGateError(
                f"suppression lock mismatch for {suppression.advisory_id}: "
                f"expected {suppression.package}=={suppression.version}, "
                f"found {sorted(actual)}"
            )


def lock_compile_command(output_path: Path) -> tuple[str, ...]:
    """Return the only supported universal worker-lock regeneration command."""
    return (
        "uv",
        "pip",
        "compile",
        "pyproject.toml",
        "--extra",
        "agent",
        "--constraints",
        CONSTRAINTS_PATH.name,
        "--overrides",
        OVERRIDES_PATH.name,
        "--python-version",
        "3.12",
        "--universal",
        "--generate-hashes",
        "--output-file",
        str(output_path),
    )


def validate_generated_lock(checked_in: str, generated: str) -> None:
    """Compare generated content while ignoring only uv's output-path header."""
    if not checked_in.startswith(LOCK_HEADER):
        raise AuditGateError("worker lock has an unexpected generation header")
    if generated.splitlines(keepends=True)[2:] != checked_in.splitlines(
        keepends=True
    )[2:]:
        raise AuditGateError(
            "requirements-agent.lock is stale; regenerate it from the "
            "reviewed constraints and overrides"
        )


def verify_lock_freshness() -> None:
    """Resolve the declared inputs and compare their generated lock body."""
    checked_in = LOCK_PATH.read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory(prefix="apdl-worker-lock-") as temp_dir:
        generated_path = Path(temp_dir) / LOCK_PATH.name
        result = subprocess.run(
            lock_compile_command(generated_path),
            cwd=CODEGEN_DIR,
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise AuditGateError(
                "worker lock regeneration failed:\n"
                + result.stderr.strip()
            )
        generated = generated_path.read_text(encoding="utf-8")
    validate_generated_lock(checked_in, generated)


def parse_audit_report(report: Any) -> tuple[Finding, ...]:
    """Parse pip-audit JSON using a fail-closed external-output schema."""
    document = _exact_fields(report, REPORT_FIELDS, "pip-audit report")
    if document["fixes"] != []:
        raise AuditGateError("pip-audit unexpectedly modified dependencies")
    dependencies = document["dependencies"]
    if not isinstance(dependencies, list):
        raise AuditGateError("pip-audit dependencies must be a list")
    findings: list[Finding] = []
    for dependency_index, raw_dependency in enumerate(dependencies):
        dependency = _exact_fields(
            raw_dependency,
            DEPENDENCY_FIELDS,
            f"pip-audit dependency {dependency_index}",
        )
        package = _canonical_package_name(
            _string(dependency["name"], "dependency name")
        )
        version = _string(dependency["version"], "dependency version")
        vulnerabilities = dependency["vulns"]
        if not isinstance(vulnerabilities, list):
            raise AuditGateError("pip-audit vulnerabilities must be a list")
        for vulnerability_index, raw_vulnerability in enumerate(vulnerabilities):
            vulnerability = _exact_fields(
                raw_vulnerability,
                VULNERABILITY_FIELDS,
                (
                    f"pip-audit vulnerability {dependency_index}:"
                    f"{vulnerability_index}"
                ),
            )
            aliases = _string_list(vulnerability["aliases"], "aliases")
            fix_versions = _string_list(
                vulnerability["fix_versions"],
                "fix_versions",
            )
            _string(vulnerability["description"], "description")
            findings.append(
                Finding(
                    advisory_id=_string(
                        vulnerability["id"],
                        "vulnerability id",
                    ),
                    package=package,
                    version=version,
                    aliases=aliases,
                    fix_versions=fix_versions,
                )
            )
    return tuple(findings)


def validate_audit_report(
    report: Any,
    suppressions: Sequence[Suppression],
) -> None:
    """Permit only exact, present, no-fix findings from the approved policy."""
    findings = parse_audit_report(report)
    seen: set[str] = set()
    for finding in findings:
        matches = [
            suppression
            for suppression in suppressions
            if suppression.advisory_id == finding.advisory_id
            or suppression.advisory_id in finding.aliases
        ]
        if not matches:
            category = "fixable" if finding.fix_versions else "unsuppressed"
            raise AuditGateError(
                f"unexpected {category} vulnerability: "
                f"{finding.package}=={finding.version} {finding.advisory_id}"
            )
        if len(matches) != 1:
            raise AuditGateError(
                f"ambiguous advisory identity: {finding.advisory_id}"
            )
        suppression = matches[0]
        if (
            finding.package != suppression.package
            or finding.version != suppression.version
        ):
            raise AuditGateError(
                f"reported package/version mismatch for "
                f"{suppression.advisory_id}: "
                f"{finding.package}=={finding.version}"
            )
        if finding.fix_versions:
            raise AuditGateError(
                f"suppressed advisory now has a fix: "
                f"{suppression.advisory_id} -> "
                f"{', '.join(finding.fix_versions)}"
            )
        seen.add(suppression.advisory_id)
    expected = {suppression.advisory_id for suppression in suppressions}
    if seen != expected:
        raise AuditGateError(
            "stale or missing advisory results; "
            f"missing={sorted(expected - seen)}"
        )


def _audit_base_command() -> list[str]:
    return [
        "uvx",
        "--python",
        "3.12",
        "pip-audit",
        "--strict",
        "--require-hashes",
        "--disable-pip",
    ]


def clean_audit_command(
    suppressions: Sequence[Suppression],
) -> tuple[str, ...]:
    """Build the final pip-audit command from the validated exact allowlist."""
    command = _audit_base_command()
    for advisory_id in sorted(
        suppression.advisory_id for suppression in suppressions
    ):
        command.extend(("--ignore-vuln", advisory_id))
    command.extend(("-r", str(LOCK_PATH)))
    return tuple(command)


def run_dependency_audit(suppressions: Sequence[Suppression]) -> None:
    """Validate the raw report, then require pip-audit's ignored gate to pass."""
    report_command = _audit_base_command()
    report_command.extend(("--format", "json", "-r", str(LOCK_PATH)))
    report_result = subprocess.run(
        report_command,
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if report_result.returncode not in {0, 1}:
        raise AuditGateError(
            "pip-audit report failed:\n" + report_result.stderr.strip()
        )
    try:
        report = json.loads(report_result.stdout)
    except json.JSONDecodeError as exc:
        raise AuditGateError("pip-audit did not return valid JSON") from exc
    validate_audit_report(report, suppressions)

    clean_result = subprocess.run(
        clean_audit_command(suppressions),
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if clean_result.stdout:
        print(clean_result.stdout, end="")
    if clean_result.stderr:
        print(clean_result.stderr, end="", file=sys.stderr)
    if clean_result.returncode != 0:
        raise AuditGateError("validated pip-audit suppression gate failed")


def main() -> int:
    if sys.version_info[:2] != (3, 12):
        raise AuditGateError("worker dependency gate requires Python 3.12")
    suppressions = load_suppressions()
    lock_text = LOCK_PATH.read_text(encoding="utf-8")
    validate_suppression_lock_versions(suppressions, lock_text)
    verify_lock_freshness()
    run_dependency_audit(suppressions)
    print("Codegen worker dependency audit passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AuditGateError as exc:
        print(f"Codegen worker dependency audit failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
